id = "wq"
name = "wq"
version = "0.1.1"
schema_version = 1
authors = ["tttiw"]
description = "Language support for wq"
repository = "https://github.com/illusory-dept/wq-zed"

[grammars.wq]
repository = "https://github.com/illusory-dept/tree-sitter-wq"
rev = "8d38698cc117035fd57b5dc54199d8a93a662bf6"
