id = "wq"
name = "wq"
version = "0.1.0"
schema_version = 1
authors = ["tttiw"]
description = "Language support for wq"
repository = "https://github.com/illusory-dept/wq-zed"

[grammars.wq]
repository = "https://github.com/illusory-dept/tree-sitter-wq"
rev = "f0a6c6d6b5b538b4d4b1a3a9dd494bf2fe396a09"
