name = "wq"
grammar = "wq"
path_suffixes = ["wq"]
line_comments = ["//"]
tab_size = 2
brackets = [
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    # quotes auto-close except when already in a string
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "string",
    ] },
    # backticks too, but not inside strings or comments
    { start = "`", end = "`", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
]
